sudo: required
dist: trusty
language: node_js
node_js:
- "8"
addons:
apt:
  sources:
  - google-chrome
  packages:
  - google-chrome-stable
  - google-chrome-beta
  - google-chrome-latest
before_install:
- export CHROME_BIN=chromium-browser
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- npm config set "@fortawesome:registry" https://npm.fontawesome.com/$FORT_AWESOME_TOKEN
script:
- npm run lint
- npm run sass-lint
- npm run ng test -- --watch=false
- npm run style
- npm run spell
- npm run build.electron.after
# - npm run e2e
- npm run build
after_success:
