sudo: required
dist: trusty
language: node_js
node_js:
- node
addons:
apt:
  sources:
  - google-chrome
  packages:
  - google-chrome-stable
  - google-chrome-beta
  - google-chrome-latest
before_install:
- export CHROME_BIN=chromium-browser
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
script:
- npm run lint
- npm run sass-lint
- npm run test
# - npm run e2e
- npm run build
after_success:
